package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.BannerPatternRegistry

object BannerPatterns {
    val BASE = BannerPatternRegistry["minecraft:base"]
    val SQUARE_BOTTOM_LEFT = BannerPatternRegistry["minecraft:square_bottom_left"]
    val SQUARE_BOTTOM_RIGHT = BannerPatternRegistry["minecraft:square_bottom_right"]
    val SQUARE_TOP_LEFT = BannerPatternRegistry["minecraft:square_top_left"]
    val SQUARE_TOP_RIGHT = BannerPatternRegistry["minecraft:square_top_right"]
    val STRIPE_BOTTOM = BannerPatternRegistry["minecraft:stripe_bottom"]
    val STRIPE_TOP = BannerPatternRegistry["minecraft:stripe_top"]
    val STRIPE_LEFT = BannerPatternRegistry["minecraft:stripe_left"]
    val STRIPE_RIGHT = BannerPatternRegistry["minecraft:stripe_right"]
    val STRIPE_CENTER = BannerPatternRegistry["minecraft:stripe_center"]
    val STRIPE_MIDDLE = BannerPatternRegistry["minecraft:stripe_middle"]
    val STRIPE_DOWNRIGHT = BannerPatternRegistry["minecraft:stripe_downright"]
    val STRIPE_DOWNLEFT = BannerPatternRegistry["minecraft:stripe_downleft"]
    val SMALL_STRIPES = BannerPatternRegistry["minecraft:small_stripes"]
    val CROSS = BannerPatternRegistry["minecraft:cross"]
    val STRAIGHT_CROSS = BannerPatternRegistry["minecraft:straight_cross"]
    val TRIANGLE_BOTTOM = BannerPatternRegistry["minecraft:triangle_bottom"]
    val TRIANGLE_TOP = BannerPatternRegistry["minecraft:triangle_top"]
    val TRIANGLES_BOTTOM = BannerPatternRegistry["minecraft:triangles_bottom"]
    val TRIANGLES_TOP = BannerPatternRegistry["minecraft:triangles_top"]
    val DIAGONAL_LEFT = BannerPatternRegistry["minecraft:diagonal_left"]
    val DIAGONAL_UP_RIGHT = BannerPatternRegistry["minecraft:diagonal_up_right"]
    val DIAGONAL_UP_LEFT = BannerPatternRegistry["minecraft:diagonal_up_left"]
    val DIAGONAL_RIGHT = BannerPatternRegistry["minecraft:diagonal_right"]
    val CIRCLE = BannerPatternRegistry["minecraft:circle"]
    val RHOMBUS = BannerPatternRegistry["minecraft:rhombus"]
    val HALF_VERTICAL = BannerPatternRegistry["minecraft:half_vertical"]
    val HALF_HORIZONTAL = BannerPatternRegistry["minecraft:half_horizontal"]
    val HALF_VERTICAL_RIGHT = BannerPatternRegistry["minecraft:half_vertical_right"]
    val HALF_HORIZONTAL_BOTTOM = BannerPatternRegistry["minecraft:half_horizontal_bottom"]
    val BORDER = BannerPatternRegistry["minecraft:border"]
    val CURLY_BORDER = BannerPatternRegistry["minecraft:curly_border"]
    val GRADIENT = BannerPatternRegistry["minecraft:gradient"]
    val GRADIENT_UP = BannerPatternRegistry["minecraft:gradient_up"]
    val BRICKS = BannerPatternRegistry["minecraft:bricks"]
    val GLOBE = BannerPatternRegistry["minecraft:globe"]
    val CREEPER = BannerPatternRegistry["minecraft:creeper"]
    val SKULL = BannerPatternRegistry["minecraft:skull"]
    val FLOWER = BannerPatternRegistry["minecraft:flower"]
    val MOJANG = BannerPatternRegistry["minecraft:mojang"]
    val PIGLIN = BannerPatternRegistry["minecraft:piglin"]
    val FLOW = BannerPatternRegistry["minecraft:flow"]
    val GUSTER = BannerPatternRegistry["minecraft:guster"]
}