package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.CatVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object CatVariants {
    val MINECRAFT:ALL_BLACK = CatVariantRegistry["minecraft:minecraft:all_black"]
    val MINECRAFT:BLACK = CatVariantRegistry["minecraft:minecraft:black"]
    val MINECRAFT:BRITISH_SHORTHAIR = CatVariantRegistry["minecraft:minecraft:british_shorthair"]
    val MINECRAFT:CALICO = CatVariantRegistry["minecraft:minecraft:calico"]
    val MINECRAFT:JELLIE = CatVariantRegistry["minecraft:minecraft:jellie"]
    val MINECRAFT:PERSIAN = CatVariantRegistry["minecraft:minecraft:persian"]
    val MINECRAFT:RAGDOLL = CatVariantRegistry["minecraft:minecraft:ragdoll"]
    val MINECRAFT:RED = CatVariantRegistry["minecraft:minecraft:red"]
    val MINECRAFT:SIAMESE = CatVariantRegistry["minecraft:minecraft:siamese"]
    val MINECRAFT:TABBY = CatVariantRegistry["minecraft:minecraft:tabby"]
    val MINECRAFT:WHITE = CatVariantRegistry["minecraft:minecraft:white"]
}
