package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.CatVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object CatVariants {
    val ALL_BLACK = CatVariantRegistry["minecraft:all_black"]
    val BLACK = CatVariantRegistry["minecraft:black"]
    val BRITISH_SHORTHAIR = CatVariantRegistry["minecraft:british_shorthair"]
    val CALICO = CatVariantRegistry["minecraft:calico"]
    val JELLIE = CatVariantRegistry["minecraft:jellie"]
    val PERSIAN = CatVariantRegistry["minecraft:persian"]
    val RAGDOLL = CatVariantRegistry["minecraft:ragdoll"]
    val RED = CatVariantRegistry["minecraft:red"]
    val SIAMESE = CatVariantRegistry["minecraft:siamese"]
    val TABBY = CatVariantRegistry["minecraft:tabby"]
    val WHITE = CatVariantRegistry["minecraft:white"]
}
