package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.ChickenVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object ChickenVariants {
    val MINECRAFT:COLD = ChickenVariantRegistry["minecraft:minecraft:cold"]
    val MINECRAFT:TEMPERATE = ChickenVariantRegistry["minecraft:minecraft:temperate"]
    val MINECRAFT:WARM = ChickenVariantRegistry["minecraft:minecraft:warm"]
}
