package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.ChickenVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object ChickenVariants {
    val COLD = ChickenVariantRegistry["minecraft:cold"]
    val TEMPERATE = ChickenVariantRegistry["minecraft:temperate"]
    val WARM = ChickenVariantRegistry["minecraft:warm"]
}
