package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.CowVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object CowVariants {
    val COLD = CowVariantRegistry["minecraft:cold"]
    val TEMPERATE = CowVariantRegistry["minecraft:temperate"]
    val WARM = CowVariantRegistry["minecraft:warm"]
}
