package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.CowVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object CowVariants {
    val MINECRAFT:COLD = CowVariantRegistry["minecraft:minecraft:cold"]
    val MINECRAFT:TEMPERATE = CowVariantRegistry["minecraft:minecraft:temperate"]
    val MINECRAFT:WARM = CowVariantRegistry["minecraft:minecraft:warm"]
}
