package io.github.dockyardmc.registry
import io.github.dockyardmc.utils.Resources
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
// THIS CLASS IS AUTO-GENERATED
// DATA FROM MINECRAFT 1.21
// https://github.com/DockyardMC/RegistryClassesGenerators

object Entities {
    private val idToEntityMap by lazy {
        val json = Json { ignoreUnknownKeys = true }
        val entities = json.decodeFromString<List<EntityType>>(Resources.getText("./data/entities.json"))
        entities.associateBy { it.id }
    }
    fun getEntityById(id: Int): EntityType {
        return idToEntityMap[id] ?: error("Entity ID $id not found")
    }
    val ALLAY = getEntityById(0)
    val AREA_EFFECT_CLOUD = getEntityById(1)
    val ARMADILLO = getEntityById(2)
    val ARMOR_STAND = getEntityById(3)
    val ARROW = getEntityById(4)
    val AXOLOTL = getEntityById(5)
    val BAT = getEntityById(6)
    val BEE = getEntityById(7)
    val BLAZE = getEntityById(8)
    val BLOCK_DISPLAY = getEntityById(9)
    val BOAT = getEntityById(10)
    val BOGGED = getEntityById(11)
    val BREEZE = getEntityById(12)
    val BREEZE_WIND_CHARGE = getEntityById(13)
    val CAMEL = getEntityById(14)
    val CAT = getEntityById(15)
    val CAVE_SPIDER = getEntityById(16)
    val CHEST_BOAT = getEntityById(17)
    val CHEST_MINECART = getEntityById(18)
    val CHICKEN = getEntityById(19)
    val COD = getEntityById(20)
    val COMMAND_BLOCK_MINECART = getEntityById(21)
    val COW = getEntityById(22)
    val CREEPER = getEntityById(23)
    val DOLPHIN = getEntityById(24)
    val DONKEY = getEntityById(25)
    val DRAGON_FIREBALL = getEntityById(26)
    val DROWNED = getEntityById(27)
    val EGG = getEntityById(28)
    val ELDER_GUARDIAN = getEntityById(29)
    val END_CRYSTAL = getEntityById(30)
    val ENDER_DRAGON = getEntityById(31)
    val ENDER_PEARL = getEntityById(32)
    val ENDERMAN = getEntityById(33)
    val ENDERMITE = getEntityById(34)
    val EVOKER = getEntityById(35)
    val EVOKER_FANGS = getEntityById(36)
    val EXPERIENCE_BOTTLE = getEntityById(37)
    val EXPERIENCE_ORB = getEntityById(38)
    val EYE_OF_ENDER = getEntityById(39)
    val FALLING_BLOCK = getEntityById(40)
    val FIREWORK_ROCKET = getEntityById(41)
    val FOX = getEntityById(42)
    val FROG = getEntityById(43)
    val FURNACE_MINECART = getEntityById(44)
    val GHAST = getEntityById(45)
    val GIANT = getEntityById(46)
    val GLOW_ITEM_FRAME = getEntityById(47)
    val GLOW_SQUID = getEntityById(48)
    val GOAT = getEntityById(49)
    val GUARDIAN = getEntityById(50)
    val HOGLIN = getEntityById(51)
    val HOPPER_MINECART = getEntityById(52)
    val HORSE = getEntityById(53)
    val HUSK = getEntityById(54)
    val ILLUSIONER = getEntityById(55)
    val INTERACTION = getEntityById(56)
    val IRON_GOLEM = getEntityById(57)
    val ITEM = getEntityById(58)
    val ITEM_DISPLAY = getEntityById(59)
    val ITEM_FRAME = getEntityById(60)
    val OMINOUS_ITEM_SPAWNER = getEntityById(61)
    val FIREBALL = getEntityById(62)
    val LEASH_KNOT = getEntityById(63)
    val LIGHTNING_BOLT = getEntityById(64)
    val LLAMA = getEntityById(65)
    val LLAMA_SPIT = getEntityById(66)
    val MAGMA_CUBE = getEntityById(67)
    val MARKER = getEntityById(68)
    val MINECART = getEntityById(69)
    val MOOSHROOM = getEntityById(70)
    val MULE = getEntityById(71)
    val OCELOT = getEntityById(72)
    val PAINTING = getEntityById(73)
    val PANDA = getEntityById(74)
    val PARROT = getEntityById(75)
    val PHANTOM = getEntityById(76)
    val PIG = getEntityById(77)
    val PIGLIN = getEntityById(78)
    val PIGLIN_BRUTE = getEntityById(79)
    val PILLAGER = getEntityById(80)
    val POLAR_BEAR = getEntityById(81)
    val POTION = getEntityById(82)
    val PUFFERFISH = getEntityById(83)
    val RABBIT = getEntityById(84)
    val RAVAGER = getEntityById(85)
    val SALMON = getEntityById(86)
    val SHEEP = getEntityById(87)
    val SHULKER = getEntityById(88)
    val SHULKER_BULLET = getEntityById(89)
    val SILVERFISH = getEntityById(90)
    val SKELETON = getEntityById(91)
    val SKELETON_HORSE = getEntityById(92)
    val SLIME = getEntityById(93)
    val SMALL_FIREBALL = getEntityById(94)
    val SNIFFER = getEntityById(95)
    val SNOW_GOLEM = getEntityById(96)
    val SNOWBALL = getEntityById(97)
    val SPAWNER_MINECART = getEntityById(98)
    val SPECTRAL_ARROW = getEntityById(99)
    val SPIDER = getEntityById(100)
    val SQUID = getEntityById(101)
    val STRAY = getEntityById(102)
    val STRIDER = getEntityById(103)
    val TADPOLE = getEntityById(104)
    val TEXT_DISPLAY = getEntityById(105)
    val TNT = getEntityById(106)
    val TNT_MINECART = getEntityById(107)
    val TRADER_LLAMA = getEntityById(108)
    val TRIDENT = getEntityById(109)
    val TROPICAL_FISH = getEntityById(110)
    val TURTLE = getEntityById(111)
    val VEX = getEntityById(112)
    val VILLAGER = getEntityById(113)
    val VINDICATOR = getEntityById(114)
    val WANDERING_TRADER = getEntityById(115)
    val WARDEN = getEntityById(116)
    val WIND_CHARGE = getEntityById(117)
    val WITCH = getEntityById(118)
    val WITHER = getEntityById(119)
    val WITHER_SKELETON = getEntityById(120)
    val WITHER_SKULL = getEntityById(121)
    val WOLF = getEntityById(122)
    val ZOGLIN = getEntityById(123)
    val ZOMBIE = getEntityById(124)
    val ZOMBIE_HORSE = getEntityById(125)
    val ZOMBIE_VILLAGER = getEntityById(126)
    val ZOMBIFIED_PIGLIN = getEntityById(127)
    val PLAYER = getEntityById(128)
    val FISHING_BOBBER = getEntityById(129)
}
@Serializable
data class EntityType(
    val id: Int,
    @SerialName("displayName")
    val name: String,
    @SerialName("name")
    val namespace: String,
    val width: Float,
    val height: Float,
    val type: String,
    val category: String
)
