package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.FrogVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object FrogVariants {
    val MINECRAFT:COLD = FrogVariantRegistry["minecraft:minecraft:cold"]
    val MINECRAFT:TEMPERATE = FrogVariantRegistry["minecraft:minecraft:temperate"]
    val MINECRAFT:WARM = FrogVariantRegistry["minecraft:minecraft:warm"]
}
