package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.JukeboxSongRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object JukeboxSongs {
    val ELEVEN = JukeboxSongRegistry["minecraft:11"]
    val THIRTEEN = JukeboxSongRegistry["minecraft:13"]
    val FIVE = JukeboxSongRegistry["minecraft:5"]
    val BLOCKS = JukeboxSongRegistry["minecraft:blocks"]
    val CAT = JukeboxSongRegistry["minecraft:cat"]
    val CHIRP = JukeboxSongRegistry["minecraft:chirp"]
    val CREATOR = JukeboxSongRegistry["minecraft:creator"]
    val CREATOR_MUSIC_BOX = JukeboxSongRegistry["minecraft:creator_music_box"]
    val FAR = JukeboxSongRegistry["minecraft:far"]
    val LAVA_CHICKEN = JukeboxSongRegistry["minecraft:lava_chicken"]
    val MALL = JukeboxSongRegistry["minecraft:mall"]
    val MELLOHI = JukeboxSongRegistry["minecraft:mellohi"]
    val OTHERSIDE = JukeboxSongRegistry["minecraft:otherside"]
    val PIGSTEP = JukeboxSongRegistry["minecraft:pigstep"]
    val PRECIPICE = JukeboxSongRegistry["minecraft:precipice"]
    val RELIC = JukeboxSongRegistry["minecraft:relic"]
    val STAL = JukeboxSongRegistry["minecraft:stal"]
    val STRAD = JukeboxSongRegistry["minecraft:strad"]
    val TEARS = JukeboxSongRegistry["minecraft:tears"]
    val WAIT = JukeboxSongRegistry["minecraft:wait"]
    val WARD = JukeboxSongRegistry["minecraft:ward"]
}
