package io.github.dockyardmc.registry
import io.github.dockyardmc.utils.Resources.getFile
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
// THIS CLASS IS AUTO-GENERATED
// DATA FROM MINECRAFT 1.21
// https://github.com/DockyardMC/RegistryClassesGenerators

object Particles {
    val idToParticleMap by lazy {
        val json = Json { ignoreUnknownKeys = true }
        val particles = json.decodeFromString<MutableList<Particle>>(getFile("data/particles.json"))
        particles.associateBy { it.id }
    }
    fun getParticleById(id: Int): Particle = idToParticleMap[id] ?: error("Particle ID $id not found")
    val ANGRY_VILLAGER = getParticleById(0)
    val BLOCK = getParticleById(1)
    val BLOCK_MARKER = getParticleById(2)
    val BUBBLE = getParticleById(3)
    val CLOUD = getParticleById(4)
    val CRIT = getParticleById(5)
    val DAMAGE_INDICATOR = getParticleById(6)
    val DRAGON_BREATH = getParticleById(7)
    val DRIPPING_LAVA = getParticleById(8)
    val FALLING_LAVA = getParticleById(9)
    val LANDING_LAVA = getParticleById(10)
    val DRIPPING_WATER = getParticleById(11)
    val FALLING_WATER = getParticleById(12)
    val DUST = getParticleById(13)
    val DUST_COLOR_TRANSITION = getParticleById(14)
    val EFFECT = getParticleById(15)
    val ELDER_GUARDIAN = getParticleById(16)
    val ENCHANTED_HIT = getParticleById(17)
    val ENCHANT = getParticleById(18)
    val END_ROD = getParticleById(19)
    val ENTITY_EFFECT = getParticleById(20)
    val EXPLOSION_EMITTER = getParticleById(21)
    val EXPLOSION = getParticleById(22)
    val GUST = getParticleById(23)
    val SMALL_GUST = getParticleById(24)
    val GUST_EMITTER_LARGE = getParticleById(25)
    val GUST_EMITTER_SMALL = getParticleById(26)
    val SONIC_BOOM = getParticleById(27)
    val FALLING_DUST = getParticleById(28)
    val FIREWORK = getParticleById(29)
    val FISHING = getParticleById(30)
    val FLAME = getParticleById(31)
    val INFESTED = getParticleById(32)
    val CHERRY_LEAVES = getParticleById(33)
    val SCULK_SOUL = getParticleById(34)
    val SCULK_CHARGE = getParticleById(35)
    val SCULK_CHARGE_POP = getParticleById(36)
    val SOUL_FIRE_FLAME = getParticleById(37)
    val SOUL = getParticleById(38)
    val FLASH = getParticleById(39)
    val HAPPY_VILLAGER = getParticleById(40)
    val COMPOSTER = getParticleById(41)
    val HEART = getParticleById(42)
    val INSTANT_EFFECT = getParticleById(43)
    val ITEM = getParticleById(44)
    val VIBRATION = getParticleById(45)
    val ITEM_SLIME = getParticleById(46)
    val ITEM_COBWEB = getParticleById(47)
    val ITEM_SNOWBALL = getParticleById(48)
    val LARGE_SMOKE = getParticleById(49)
    val LAVA = getParticleById(50)
    val MYCELIUM = getParticleById(51)
    val NOTE = getParticleById(52)
    val POOF = getParticleById(53)
    val PORTAL = getParticleById(54)
    val RAIN = getParticleById(55)
    val SMOKE = getParticleById(56)
    val WHITE_SMOKE = getParticleById(57)
    val SNEEZE = getParticleById(58)
    val SPIT = getParticleById(59)
    val SQUID_INK = getParticleById(60)
    val SWEEP_ATTACK = getParticleById(61)
    val TOTEM_OF_UNDYING = getParticleById(62)
    val UNDERWATER = getParticleById(63)
    val SPLASH = getParticleById(64)
    val WITCH = getParticleById(65)
    val BUBBLE_POP = getParticleById(66)
    val CURRENT_DOWN = getParticleById(67)
    val BUBBLE_COLUMN_UP = getParticleById(68)
    val NAUTILUS = getParticleById(69)
    val DOLPHIN = getParticleById(70)
    val CAMPFIRE_COSY_SMOKE = getParticleById(71)
    val CAMPFIRE_SIGNAL_SMOKE = getParticleById(72)
    val DRIPPING_HONEY = getParticleById(73)
    val FALLING_HONEY = getParticleById(74)
    val LANDING_HONEY = getParticleById(75)
    val FALLING_NECTAR = getParticleById(76)
    val FALLING_SPORE_BLOSSOM = getParticleById(77)
    val ASH = getParticleById(78)
    val CRIMSON_SPORE = getParticleById(79)
    val WARPED_SPORE = getParticleById(80)
    val SPORE_BLOSSOM_AIR = getParticleById(81)
    val DRIPPING_OBSIDIAN_TEAR = getParticleById(82)
    val FALLING_OBSIDIAN_TEAR = getParticleById(83)
    val LANDING_OBSIDIAN_TEAR = getParticleById(84)
    val REVERSE_PORTAL = getParticleById(85)
    val WHITE_ASH = getParticleById(86)
    val SMALL_FLAME = getParticleById(87)
    val SNOWFLAKE = getParticleById(88)
    val DRIPPING_DRIPSTONE_LAVA = getParticleById(89)
    val FALLING_DRIPSTONE_LAVA = getParticleById(90)
    val DRIPPING_DRIPSTONE_WATER = getParticleById(91)
    val FALLING_DRIPSTONE_WATER = getParticleById(92)
    val GLOW_SQUID_INK = getParticleById(93)
    val GLOW = getParticleById(94)
    val WAX_ON = getParticleById(95)
    val WAX_OFF = getParticleById(96)
    val ELECTRIC_SPARK = getParticleById(97)
    val SCRAPE = getParticleById(98)
    val SHRIEK = getParticleById(99)
    val EGG_CRACK = getParticleById(100)
    val DUST_PLUME = getParticleById(101)
    val TRIAL_SPAWNER_DETECTION = getParticleById(102)
    val TRIAL_SPAWNER_DETECTION_OMINOUS = getParticleById(103)
    val VAULT_CONNECTION = getParticleById(104)
    val DUST_PILLAR = getParticleById(105)
    val OMINOUS_SPAWNING = getParticleById(106)
    val RAID_OMEN = getParticleById(107)
    val TRIAL_OMEN = getParticleById(108)
}
@Serializable
data class Particle(
    val id: Int,
    @SerialName("name")
    val namespace: String
)
