package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.PigVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object PigVariants {
    val MINECRAFT:COLD = PigVariantRegistry["minecraft:minecraft:cold"]
    val MINECRAFT:TEMPERATE = PigVariantRegistry["minecraft:minecraft:temperate"]
    val MINECRAFT:WARM = PigVariantRegistry["minecraft:minecraft:warm"]
}
