package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.TrimMaterialRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object TrimMaterials {
    val AMETHYST = TrimMaterialRegistry["minecraft:amethyst"]
    val COPPER = TrimMaterialRegistry["minecraft:copper"]
    val DIAMOND = TrimMaterialRegistry["minecraft:diamond"]
    val EMERALD = TrimMaterialRegistry["minecraft:emerald"]
    val GOLD = TrimMaterialRegistry["minecraft:gold"]
    val IRON = TrimMaterialRegistry["minecraft:iron"]
    val LAPIS = TrimMaterialRegistry["minecraft:lapis"]
    val NETHERITE = TrimMaterialRegistry["minecraft:netherite"]
    val QUARTZ = TrimMaterialRegistry["minecraft:quartz"]
    val REDSTONE = TrimMaterialRegistry["minecraft:redstone"]
    val RESIN = TrimMaterialRegistry["minecraft:resin"]
}
