package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.TrimPatternRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object TrimPatterns {
    val BOLT = TrimPatternRegistry["minecraft:bolt"]
    val COAST = TrimPatternRegistry["minecraft:coast"]
    val DUNE = TrimPatternRegistry["minecraft:dune"]
    val EYE = TrimPatternRegistry["minecraft:eye"]
    val FLOW = TrimPatternRegistry["minecraft:flow"]
    val HOST = TrimPatternRegistry["minecraft:host"]
    val RAISER = TrimPatternRegistry["minecraft:raiser"]
    val RIB = TrimPatternRegistry["minecraft:rib"]
    val SENTRY = TrimPatternRegistry["minecraft:sentry"]
    val SHAPER = TrimPatternRegistry["minecraft:shaper"]
    val SILENCE = TrimPatternRegistry["minecraft:silence"]
    val SNOUT = TrimPatternRegistry["minecraft:snout"]
    val SPIRE = TrimPatternRegistry["minecraft:spire"]
    val TIDE = TrimPatternRegistry["minecraft:tide"]
    val VEX = TrimPatternRegistry["minecraft:vex"]
    val WARD = TrimPatternRegistry["minecraft:ward"]
    val WAYFINDER = TrimPatternRegistry["minecraft:wayfinder"]
    val WILD = TrimPatternRegistry["minecraft:wild"]
}
