package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.WolfVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object WolfVariants {
    val ASHEN = WolfVariantRegistry["minecraft:ashen"]
    val BLACK = WolfVariantRegistry["minecraft:black"]
    val CHESTNUT = WolfVariantRegistry["minecraft:chestnut"]
    val PALE = WolfVariantRegistry["minecraft:pale"]
    val RUSTY = WolfVariantRegistry["minecraft:rusty"]
    val SNOWY = WolfVariantRegistry["minecraft:snowy"]
    val SPOTTED = WolfVariantRegistry["minecraft:spotted"]
    val STRIPED = WolfVariantRegistry["minecraft:striped"]
    val WOODS = WolfVariantRegistry["minecraft:woods"]
}
