package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.WolfSoundVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object WolfSoundVariants {
    val MINECRAFT:ANGRY = WolfSoundVariantRegistry["minecraft:minecraft:angry"]
    val MINECRAFT:BIG = WolfSoundVariantRegistry["minecraft:minecraft:big"]
    val MINECRAFT:CLASSIC = WolfSoundVariantRegistry["minecraft:minecraft:classic"]
    val MINECRAFT:CUTE = WolfSoundVariantRegistry["minecraft:minecraft:cute"]
    val MINECRAFT:GRUMPY = WolfSoundVariantRegistry["minecraft:minecraft:grumpy"]
    val MINECRAFT:PUGLIN = WolfSoundVariantRegistry["minecraft:minecraft:puglin"]
    val MINECRAFT:SAD = WolfSoundVariantRegistry["minecraft:minecraft:sad"]
}
