package io.github.dockyardmc.registry

import io.github.dockyardmc.registry.registries.WolfVariantRegistry


// THIS CLASS IS AUTOMATICALLY GENERATED BY THE REGISTRY DATA GENERATOR
object WolfVariants {
    val MINECRAFT:ASHEN = WolfVariantRegistry["minecraft:minecraft:ashen"]
    val MINECRAFT:BLACK = WolfVariantRegistry["minecraft:minecraft:black"]
    val MINECRAFT:CHESTNUT = WolfVariantRegistry["minecraft:minecraft:chestnut"]
    val MINECRAFT:PALE = WolfVariantRegistry["minecraft:minecraft:pale"]
    val MINECRAFT:RUSTY = WolfVariantRegistry["minecraft:minecraft:rusty"]
    val MINECRAFT:SNOWY = WolfVariantRegistry["minecraft:minecraft:snowy"]
    val MINECRAFT:SPOTTED = WolfVariantRegistry["minecraft:minecraft:spotted"]
    val MINECRAFT:STRIPED = WolfVariantRegistry["minecraft:minecraft:striped"]
    val MINECRAFT:WOODS = WolfVariantRegistry["minecraft:minecraft:woods"]
}
